[package]
name = "plant-monitoring-server"
version = "0.1.0"
edition = "2018"

[dependencies]
axum = "0.5"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.5", features = ["sqlite", "async-std"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
